// Código secreto board words: short nouns, many with more than one meaning
// (banco, carta, pila…), which is what makes good clues possible.

export const CODIGO_WORDS = [
  "agente", "aguja", "ala", "alfombra", "ángel", "anillo", "araña", "arco", "ardilla", "arena",
  "ataque", "auto", "avión", "ballena", "banco", "banda", "bandera", "barco", "batería", "bomba",
  "bota", "botón", "brazo", "bruja", "caballo", "cabeza", "cadena", "caja", "cama", "cámara",
  "campana", "canal", "cancha", "cangrejo", "capa", "cara", "carta", "casco", "castillo", "cebolla",
  "cementerio", "centro", "cerebro", "cerveza", "chocolate", "cielo", "cine", "cinta", "circo", "ciudad",
  "clave", "club", "cohete", "cola", "colegio", "cometa", "corazón", "corona", "correo", "corte",
  "cráter", "cruz", "cuadro", "cubo", "cuello", "cuerda", "cuerno", "dedo", "delfín", "diamante",
  "diente", "dinosaurio", "disco", "doctor", "dragón", "ducha", "duende", "eje", "ejército", "embajada",
  "enano", "enfermera", "escala", "escuela", "espada", "espejo", "espía", "estación", "estrella", "fantasma",
  "faro", "fiesta", "flauta", "foco", "fuego", "fuente", "gato", "gigante", "globo", "gol",
  "gorila", "granja", "grúa", "guante", "guerra", "helado", "hielo", "hoja", "hongo", "hospital",
  "hotel", "huevo", "iglesia", "imán", "isla", "jamón", "jardín", "jefe", "jirafa", "juego",
  "juguete", "ladrón", "lago", "láser", "lata", "leche", "lengua", "león", "ley", "libro",
  "lima", "limón", "línea", "llave", "lluvia", "lobo", "luna", "luz", "madre", "mago",
  "mano", "manzana", "mapa", "mar", "marco", "mariposa", "mármol", "máscara", "masa", "mate",
  "médico", "mercado", "mesa", "metro", "miel", "mina", "misil", "molino", "momia", "mono",
  "montaña", "mosca", "muela", "muñeca", "museo", "música", "nariz", "nave", "nieve", "ninja",
  "noche", "nota", "nube", "nudo", "obra", "ojo", "ola", "olla", "ópera", "oro",
  "oso", "palma", "palo", "pan", "pantalla", "papel", "paracaídas", "parque", "pasaporte", "pasta",
  "pata", "pato", "pavo", "pelota", "perfume", "perro", "pez", "piano", "pico", "pie",
  "piedra", "pila", "piloto", "pingüino", "pino", "pirámide", "pirata", "pista", "planta", "plato",
  "playa", "pluma", "policía", "polo", "pozo", "princesa", "prisión", "puente", "puerta", "pulpo",
  "punto", "queso", "radio", "raíz", "rana", "rata", "ratón", "rayo", "red", "regla",
  "reina", "reloj", "rey", "río", "robot", "roca", "rosa", "rueda", "sal", "salsa",
  "sartén", "satélite", "serpiente", "sierra", "silla", "sirena", "sobre", "sol", "soldado", "sombra",
  "sombrero", "submarino", "tabla", "taxi", "teatro", "teclado", "tela", "teléfono", "tenedor", "tiburón",
  "tienda", "tierra", "tigre", "tinta", "toro", "torre", "tortuga", "tren", "triángulo", "trompeta",
  "tubo", "tumba", "unicornio", "uva", "vaca", "vampiro", "vaso", "vela", "ventana", "vida",
  "vino", "violín", "volcán", "yate", "zapato", "zorro",
];
